GET http://localhost:3000/test

###

POST http://localhost:3000/auth/register HTTP/1.1
content-type: application/json

{
    "firstName": "Prasis",
    "lastName": "Upreti",
    "email": "prasis@gmail.com",
    "password": "123456",
    "isAdmin": true
}

###

POST http://localhost:3000/auth/login HTTP/1.1
content-type: application/json

{
    "email": "prasis@gmail.com",
    "password": "123456"
}

###

POST http://localhost:3000/sources HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJwcmFzaXNAZ21haWwuY29tIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjE2Njc5ODE2LCJleHAiOjE2MTcyODQ2MTZ9.3sBN7fL1fa6NzBdwdchMkrragvGd-ES4sUDZ4Zv-T_o
content-type: application/json

{
	"name": "OkDam",
	"url": "http://okdam.com"
}

###
GET http://localhost:3000/sources?page=1&perPage=5 HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJwcmFzaXNAZ21haWwuY29tIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjE2Njc5ODE2LCJleHAiOjE2MTcyODQ2MTZ9.3sBN7fL1fa6NzBdwdchMkrragvGd-ES4sUDZ4Zv-T_o
content-type: application/json

###
GET http://localhost:3000/users HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJwcmFzaXNAZ21haWwuY29tIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjE2Njc5ODE2LCJleHAiOjE2MTcyODQ2MTZ9.3sBN7fL1fa6NzBdwdchMkrragvGd-ES4sUDZ4Zv-T_o
content-type: application/json

###
GET http://localhost:3000/products?page=4&perPage=5 HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJwcmFzaXNAZ21haWwuY29tIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjE2Njc5ODE2LCJleHAiOjE2MTcyODQ2MTZ9.3sBN7fL1fa6NzBdwdchMkrragvGd-ES4sUDZ4Zv-T_o
content-type: application/json

###
POST http://localhost:3000/products HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJwcmFzaXNAZ21haWwuY29tIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjE2Njc5ODE2LCJleHAiOjE2MTcyODQ2MTZ9.3sBN7fL1fa6NzBdwdchMkrragvGd-ES4sUDZ4Zv-T_o
content-type: application/json

{
	"productName": "Samsung 32 Inch UA32N4003ARSHE Television",
	"productLink": "https://www.sastodeal.com/samsung-32-inch-ua32n4003arshe-television-him-sam-tv-2.html",
	"price": 26500,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/3/_/3_135.jpg"
}

### 
POST http://localhost:3000/products/bulk HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJwcmFzaXNAZ21haWwuY29tIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjE2Njc5ODE2LCJleHAiOjE2MTcyODQ2MTZ9.3sBN7fL1fa6NzBdwdchMkrragvGd-ES4sUDZ4Zv-T_o
content-type: application/json

[{
	"productName": "Samsung 32 Inch UA32N4003ARSHE Television",
	"productLink": "https://www.sastodeal.com/samsung-32-inch-ua32n4003arshe-television-him-sam-tv-2.html",
	"price": 26500,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/3/_/3_135.jpg"
}, {
	"productName": "Samsung 40 Inch UA40N5000ARSHE Full HD LED TV",
	"productLink": "https://www.sastodeal.com/samsung-40-inch-ua40n5000arshe-full-hd-led-tv-him-sam-tv-4.html",
	"price": 49623,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/8/_/8_16_2.jpg"
}, {
	"productName": "Samsung UA49N5300ARSHE 49 Inch Smart Full HD LED TV Black",
	"productLink": "https://www.sastodeal.com/samsung-ua49n5300arshe-49-inch-smart-full-hd-led-tv-black-him-sam-tv-6.html",
	"price": 76815,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/1/2/12_2_4.jpg"
}, {
	"productName": "Samsung UA43NU7100RSHE 43 Inch Smart UHD LED TV Black",
	"productLink": "https://www.sastodeal.com/samsung-ua43nu7100rshe-43-smart-uhd-led-tv-black-him-sam-tv-7.html",
	"price": 81391,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/1/3/13a_1.png"
}, {
	"productName": "Samsung UA43RU7100RSHE 43 Inch Smart 4K UHD LED TV Black",
	"productLink": "https://www.sastodeal.com/samsung-ua43ru7100rshe-43-smart-4k-uhd-led-tv-black-him-sam-tv-8.html",
	"price": 81391,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/1/4/14_4_3.jpg"
}, {
	"productName": "Samsung UA49NU7100RSHE 49 Inch Smart UHD LED TV Black",
	"productLink": "https://www.sastodeal.com/samsung-ua49nu7100rshe-49-smart-uhd-led-tv-black-him-sam-tv-9.html",
	"price": 113247,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/1/6/16_7.jpg"
}, {
	"productName": "Samsung UA49RU7100RSHE 49 Inch Smart 4K UHD LED TV Black",
	"productLink": "https://www.sastodeal.com/samsung-ua49ru7100rshe-49-smart-4k-uhd-led-tv-black-him-sam-tv-10.html",
	"price": 113247,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/1/7/17_1_3.jpg"
}, {
	"productName": "Samsung Ultra HD LED 55 Inch Smart TV UA55RU7100",
	"productLink": "https://www.sastodeal.com/samsung-ultra-hd-led-55-inch-smart-tv-ua55ru7100-him-sam-tv-11.html",
	"price": 134279,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/1/9/19_2.jpg"
}, {
	"productName": "Samsung Ultra HD LED 65 Inch Smart TV with Built-in Receiver 4K UA65RU7100",
	"productLink": "https://www.sastodeal.com/samsung-ultra-hd-led-65-inch-smart-tv-with-built-in-receiver-4k-ua65ru7100-him-sam-tv-12.html",
	"price": 206351,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/2/0/20.png"
}, {
	"productName": "Samsung 55 Inch QLED Ultra HD Premium HDR Smart Led TV QA55Q60RARXHE",
	"productLink": "https://www.sastodeal.com/samsung-55-inch-qled-ultra-hd-premium-hdr-smart-led-tv-qa55q60rarxhe-him-sam-tv-13.html",
	"price": 273671,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/1/_/1_12_1.png"
}, {
	"productName": "Samsung 65-Inch Flat Smart 4K UHD TV QA65Q60RA",
	"productLink": "https://www.sastodeal.com/samsung-65-inch-flat-smart-4k-uhd-tv-qa65q60ra-him-sam-tv-14.html",
	"price": 351991,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/1/_/1_12.png"
}, {
	"productName": "Samsung 55 Inch QLED Ultra HD Premium HDR Smart Led TV QA55Q7F",
	"productLink": "https://www.sastodeal.com/samsung-55-inch-qled-ultra-hd-premium-hdr-smart-led-tv-qa55q7f-him-sam-tv-15.html",
	"price": 466391,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/2/6/26.png"
}, {
	"productName": "Samsung 65 Inch Curved QLED Ultra HD Premium HDR 1500 Smart Led TV QA65Q7",
	"productLink": "https://www.sastodeal.com/samsung-65-inch-curved-qled-ultra-hd-premium-hdr-1500-smart-led-tv-qa65q7-him-sam-tv-16.html",
	"price": 695191,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/2/7/27.png"
}, {
	"productName": "Samsung Q60R 82 inch 4K Ultra HD Smart QLED TV - QA82Q60R",
	"productLink": "https://www.sastodeal.com/samsung-q60r-82-inch-4k-ultra-hd-smart-qled-tv-qa82q60r-him-sam-tv-17.html",
	"price": 703991,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/9540/HIM-SAM-TV-17/28a.jpg"
}, {
	"productName": "Samsung Ua43N5300 43 Inch Full Hd Led Smart Tv",
	"productLink": "https://www.sastodeal.com/samsung-ua43n5300-43-inch-full-hd-led-smart-tv-sd-ue-sam-tv-2.html",
	"price": 47500,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/14259/SD-UE-SAM-TV-2/3.jpg"
}, {
	"productName": "Samsung UA55TU8000 Crystal UHD 55 Inch 4K Smart LED TV",
	"productLink": "https://www.sastodeal.com/samsung-ua55tu8000-crystal-uhd-55-inch-4k-smart-led-tv-rn-sam-bor-3-rn-sam-bor-3-rn-sam-bor-3-rn-sam-bor-3-rn-sam-bor-3-rn-sam-bor-3-rn-sam-bor-3-rn-sam-bor-3-rn-sam-bor-3-rn-sam-bor-3-rn-sam-bor-3-rn-sam-bor-3.html",
	"price": 99000,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/14343/RN-SAM-"
}, {
	"productName": "Samsung Led TV 24 Inch UA24H4003",
	"productLink": "https://www.sastodeal.com/samsung-led-tv-24-inch-ua24h4003-smsm-ua24h4003.html",
	"price": 22041,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/u/a/ua-24h4003-1_1_.jpg"
}, {
	"productName": "Samsung 32 Inch Television UA32N4003ARSHE",
	"productLink": "https://www.sastodeal.com/samsung-32-inch-television-ua32n4003arshe-tvv-byyp-ua32n4003arshe.html",
	"price": 30141,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/3/c/3c_1_2.jpg"
}, {
	"productName": "Samsung 32″ Smart HD LED TV UA32N4300ARSHE",
	"productLink": "https://www.sastodeal.com/samsung-32-smart-hd-led-tv-ua32n4300arshe-trb-vvv-2-ua32n4300arshe.html",
	"price": 42921,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/5/a/5a_7_1.jpg"
}, {
	"productName": "Samsung 32''Smart LED TV UA32T4500",
	"productLink": "https://www.sastodeal.com/samsung-32-smart-led-tv-ua32t4500-tbh-byop-5-ua32t4500.html",
	"price": 44991,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/1/_/1_1933.jpg"
}, {
	"productName": "Samsung 40 Inch Full Hd Smart Led Tv Ua40N5000Arshe",
	"productLink": "https://www.sastodeal.com/samsung-40-inch-full-hd-smart-led-tv-ua40n5000arshe-tvv-bapo-7-ua40n5000arshe.html",
	"price": 50751,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/4/0/40_4.jpg"
}, {
	"productName": "Samsung 43″ Smart Full HD LED TV UA43N5300ARSHE",
	"productLink": "https://www.sastodeal.com/samsung-43-smart-full-hd-led-tv-ua43n5300arshe-tri-bpyr-43-ua43n5300arshe.html",
	"price": 66681,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/s/a/samsung-ua43n5300arshe.jpg"
}, {
	"productName": "Samsung 43″ Smart LED TV-UA43T5400",
	"productLink": "https://www.sastodeal.com/samsung-43-smart-led-tv-ua43t5400-tvv-bpr-09-ua43t5400.html",
	"price": 67941,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/2/b/2b6d0b18aff6bcda5cb79fba3aa3f03d_1_.jpg"
}, {
	"productName": "Samsung 43\" (108 cm) Smart Full HD LED TV UA43T5500",
	"productLink": "https://www.sastodeal.com/samsung-43-108-cm-smart-full-hd-led-tv-ua43t5500-tvv-04-ua43t5500.html",
	"price": 70191,
	"source": "Sastodeal",
	"imageUrl": "https://cdn.sastodeal.com/catalog/product/i/n/in-full-hd-tv-t5500-ua43t5500akxxl-ua--r----auxxl-227105592.jpg"
}]

###

PUT http://localhost:3000/profile/update HTTP/1.1
x-auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJwcmFzaXNAZ21haWwuY29tIiwiaXNBZG1pbiI6dHJ1ZSwiaWF0IjoxNjE2Njc5ODE2LCJleHAiOjE2MTcyODQ2MTZ9.3sBN7fL1fa6NzBdwdchMkrragvGd-ES4sUDZ4Zv-T_o
content-type: application/json

{
	"firstName": "Prasis",
	"lastName": "Upreti"
}